on:
  push:
    tags:
      - '*.*.*'

name: Create Release

# @see https://github.com/ncipollo/release-action
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    strategy:
      fail-fast: true
    name: Create Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-environment-variable
      - name: Get the tag/version
        run: |
          echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Create artifacts
        run: |
          ./bin/create-release "$GIT_TAG"

      - name: Create release body
        run: |
          echo "# Version $GIT_TAG" > body.md

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          artifacts: "leantime-dataexport-*.tar.gz,checksum.txt"
          bodyFile: "body.md"
